Verify Http/2 support
quarkus-qe/quarkus-openshift-test-suite pull request #146
Opened 2020-12-15 15:23 UTC by pjgg

Conclusion (preview):

Server: We support Http/2
HttpClient: We don't support Http/2
RestAssurance: doesn't support Http/2

### How we test it:

Server: 

We use an external client that supports Http/2 (Vertx WebClient), and we are checking that the response http version is Http 2.
RestAssurance was discarded, because after several configurations and iterations, we could not make it works. Finally, we found an [open issue](https://github.com/rest-assured/rest-assured/issues/1218) that talks about this. 

Client:
We have used Quarkus `quarkus-rest-client` synchronous and asynchronous (mutiny). We made a request, and on the server-side, we recover the HttpRequest protocol version and then return this version as a response header.

2020-12-18 15:36 UTC, rsvoboda requested changes

2020-12-18 15:36 UTC, rsvoboda commented on http/src/main/resources/application.properties
> +quarkus.s2i.base-jvm-image=quay.io/jcarvaja/openjdk-11-rhel7
why ?

2020-12-18 15:36 UTC, rsvoboda commented on http/src/main/resources/application.properties
> +quarkus.kubernetes.readiness-probe.initial-delay=5s
what's the motivation for this change?

2020-12-18 15:36 UTC, rsvoboda commented on http/src/test/java/io/quarkus/ts/openshift/http/HttpOpenShiftIT.java
> +        System.setProperty("OpenShiftIT", "true");
Why is this property set here?

2020-12-18 15:36 UTC, rsvoboda commented on http/src/test/resources/application.properties
> +
Why is this file introduced when `http/src/main/resources/application.properties` is also used / available?

2020-12-23 12:49 UTC, rsvoboda approved these changes

2020-12-23 12:51 UTC, rsvoboda commented
@Sgitario please review this PR. Feel free to merge it, I have no additional comments to it.

Just for the record I didn't check it against OpenShift instance, I rely on the author that he checked that with the latest changes too.

2020-12-23 12:54 UTC, Sgitario approved these changes
lgtm as well

2020-12-23 12:59 UTC, rsvoboda commented
Thanks, merging.

2020-12-23 12:59 UTC, merged

2021-01-05 12:08 UTC, Ladicek commented
I'm a wee disgruntled with this change. The `http` module was a nice little smoke test that I could use to verify if environment is set up properly, because the test is so basic that nothing can go wrong in it. And now you add HTTP/2 and gRPC to it. IMHO, that should have been a separate module.

2021-01-05 13:06 UTC, rsvoboda commented
that's a good point, with this merged we do not have dummy thing to ensure env is not broken (a lot).
@pjgg can you move your changes to dedicated http2 module via new PR?