Second RHDG scenario - simple failover
quarkus-qe/quarkus-openshift-test-suite pull request #158
Opened 2021-01-18 12:08 UTC by mirostary

The same Quarkus application - kill the Quarkus pod, wait for redeployment, and retrieve data.

- `InfinispanClientApp` updated with the condition preventing rewriting the cache
-  Added the third test for Quarkus pod killing - using the same approach as in configmap tests
-  Updated readme
-  Added `native.quarkus.openshift.mounts.app-config.path` to the `application.properties` for native builds

2021-01-18 12:10 UTC, mirostary commented
I can't assign anybody to the PR. @mjurc please take a look at this, thanks.

2021-01-18 12:12 UTC, Ladicek commented
You really want the directory structure to mirror the package structure :-)

2021-01-19 08:10 UTC, mirostary commented
Thanks, now it should be ok

2021-01-21 16:30 UTC, rsvoboda commented
@jsmrcka don't be afraid, for you it fine just to check that you can run those tests. Main review is on @mjurc .

2021-01-26 14:51 UTC, mjurc requested changes
This, in my opinion, tests whether the applications can read from cache rather than fail-over and data consistency. I would certainly add some checks for data consistency too:

- add server logic that modifies the data in cache and call endpoint that invokes that, for example an endpoint that functions as a request counter (easiest example would be taking a number from cache and incrementing it by one)
- invoke endpoint on node, make the node fail, check data consistency (like if the increment was processed or no)
- invoke endpoint on failed node, see whether the response of the cluster is what we expect it to be.

2021-01-26 14:58 UTC, mjurc commented on infinispan-client/src/main/java/io/quarkus/ts/openshift/infinispan/client/InfinispanFirstGreetingResource.java
>          cache.put("hello","Hello World, Infinispan is up and changed!");
With regards to my review, the change would be `counter++` instead of just `cache.put()`

2021-01-26 14:58 UTC, mjurc commented on infinispan-client/src/test/java/io/quarkus/ts/openshift/infinispan/client/InfinispanGreetingResourceOpenShiftIT.java
> +                .body(is("Hello World, Infinispan is up and changed!"));
...and here, we'd assume the number of requests on counter is what we expect it to be :)

2021-01-29 12:09 UTC, rsvoboda commented
@mirostary any news regarding this PR?

2021-01-29 12:14 UTC, mirostary commented
@rsvoboda just waiting for a test run to finish and I'll send a new commit ;)

2021-01-29 12:41 UTC, mirostary commented
@mjurc Thank you for the review, I hope I did what you meant. I tried to use the counter also without saving it to cache but I wasn't able to access it from tests... I also reduced the number of cluster replicas to 1 for faster launching and to avoid cluster restart problems in the next future tests.

2021-02-01 11:56 UTC, mjurc commented
@mirostary Right. What the fail-over test should do is:

- have multiple clients access the data in cache and modify it
- introduce a kind of failure (either in cache or a client)
- verify that the clients and the cache have consistent data

In this case, this means that the test has counter, the apps have counter and the cache has a request counter. This counter increases with each request done to app, and is then pushed into the cache. And even after the failure, the cache should ensure that all clients have consistent data.

2021-02-08 16:07 UTC, mirostary commented
@mjurc This PR is ready for review now. Up here, In my first comment, is an updated description of all tests. The multiple client access tests will be in the next PR.

2021-02-14 23:22 UTC, mjurc approved these changes
Thanks for PR.

LGTM! :)

2021-02-15 07:55 UTC, rsvoboda commented
@mjurc can it be merged? 

@jsmrcka did you look into this PR (see my comment from January 25) ?

2021-02-15 08:19 UTC, mjurc commented
I'd say yes, just didn't want to merge it with awaiting review.

2021-02-15 15:35 UTC, jsmrcka approved these changes

2021-02-16 07:02 UTC, merged