Resolve retrofit pom version conflict
quarkus-qe/quarkus-openshift-test-suite pull request #283
Opened 2021-05-07 07:56 UTC by pjgg

2021-05-07 11:50 UTC, rsvoboda requested changes
Put it into dependency management, no explicit versions in modules pls.
https://github.com/quarkus-qe/quarkus-openshift-test-suite/blob/main/pom.xml#L86

2021-05-07 11:51 UTC, rsvoboda commented
@pjgg reminder about description of the PR ... https://gitlab.cee.redhat.com/quarkus-qe/signpost/-/blob/main/pull-requests.md#main-rule-set-for-pull-requests

2021-05-12 05:14 UTC, Sgitario requested changes
Same comment as @rsvoboda .

2021-05-13 05:14 UTC, Sgitario requested changes

2021-05-13 05:14 UTC, Sgitario commented on pom.xml
> +            <dependency>
Please, add the comment here: 
```
<!-- TODO: com.squareup.retrofit2:retrofit:2.9.0 should be removed on Quarkus 2.0.0.Alphas-->
```

2021-05-13 05:14 UTC, Sgitario commented on messaging/kafka-avro-reactive-messaging/pom.xml
> +        </dependency>
We don't need to explicitly add this dependency here. Adding it into the dependency management is enough.

2021-05-13 08:11 UTC, Sgitario requested changes

2021-05-13 08:11 UTC, Sgitario commented on common/src/main/java/io/quarkus/ts/openshift/common/deploy/UsingQuarkusPluginDeploymentStrategy.java
> +    private static final void withQuarkusVersions(List<String> args) {
These format changes are unexpected, can you check why these were introduced?

2021-05-13 12:28 UTC, Sgitario approved these changes

2021-05-13 12:28 UTC, merged